### ISSUE TITLE
Praetor's Scythe in off_hand right-click error 

### ISSUE THREAD

**Issue by 6371peter** [cojalexandru/sanguine_arsenal#1]
Forge:36.2.35
MOD Version:0.0.8
Another MOD:
1.Curios-4.0.82
2.eidolon-0.2.7

When I put Praetor's Scythe in off_hand and right_click,Praetor's Scythe will flying out but it still in off_hand,when it return back it will back to my inventory.After Praetor's Scythe return back I have two Praetor's Scythe.When main_hand hold item and right_click,main_hand item will be clear and other situations are consistent with the above.

**Comment by 6371peter** [comment]
![2022-05-07_22 32 42](https://user-images.githubusercontent.com/64669376/167258859-d9fc3702-93cf-48c9-8afd-3d8679c9473b.png)
Praetor's Scythe flying out but it still in my off_hand.
![2022-05-07_22 37 00](https://user-images.githubusercontent.com/64669376/167258928-79836fee-534b-4586-85c7-193a7fb331dd.png)
After it return back I have two Praetor's Scythe.
But when I drop one of them or put it in chest,another will disappear,but if save and quit to title then Re enter the game,two Praetor's Scythe in my inventory will be save.

**Comment by cojalexandru** [comment]
Hey, thanks for the bug report! Apparently I've already had fixed this issue but because of how I formatted the code the program that I use to save it decided to simplify that part and broke it back.

This will be fixed in the next update!
